---
author: 손지우
date: "2023-01-04"
tags: null
title: Geometric SMOTE
---

Douzas, G., & Bacao, F. (2019). Geometric SMOTE a geometrically enhanced drop-in replacement for SMOTE. Information Sciences, 501, 118-135. <!--more-->

## In Short

## 1. Introduction

## 2. Related Work

### 2-1. Modifications of the selection phase

### 2-2. Modifications of the data generation mechanism

## 3. Motivation

1.  Generation of noisy instances due to the selection of k-nearest neighbors

2.  Generation of noisy examples due to the selection of an initial observation

3.  Generation of nearly duplicated instances

4.  Generation of noisy instances due to the use of observations from two different minority class clusters.

## 4. Proposed Method

1.  To define a safe area around each selected minority class instance such that the generated artificial minority instances inside the are are not noisy.
2.  To increase the variety of generated samples by expanding the minority class area.
3.  To parameterize the above characteristics based on a small number of transformations with a geometrical interpretation.

### 4-1. G-SMOTE Algorithm

### 4-2. Functions
`Surface`
`Hyperball`
`Vectors`
`Truncate`
`Deform`
`Translate`

### 4-3. Justification of the Algorithm

1. $S_{gen}$


## 5. Research Methodology

### 5-1. Experimental Data
### 5-2. Evaluation Measures
### 5-3. Machine Learning Algorithms
### 5-4. Experimental Procedure
### 5-5. Software Implementation

## 6. Results and Discussion

### 6-1. Comparative Presentation 
### 6-2. Statistical Analysis
### 6-3. G-SMOTE taxonomy
### 6-4. Analysis and Tuning of optimal hyper-parameters

## 7. Conclusions

# ---

## Critical Point (MY OWN OPINION)
